function onSessionIncomingAlert(p1 = null, p2 = null, p3 = null){};
function onSessionEstablish(p1 = null, p2 = null, p3 = null){};
//function isContinuousPaly(p1 = null, p2 = null, p3 = null){};
function pushWarningFence(p1 = null){};
function mouseDownOrUpRecord(p){};
function $(s){};
function str_select_store_path(){};
function Toast(p1, p2){};
function str_select_save_path(){};
function getCurrentCallSessionArrayId(p1 = null, p2 = null, p3 = null){};
function onTagList(p1 = null, p2 = null, p3 = null){};
function doVoicePress(p1 = null, p2 = null, p3 = null){};
function CurrentCallSessionArray(p1 = null, p2 = null, p3 = null){};
function onLogin(p1 = null, p2 = null, p3 = null){};
function onLogout(p1 = null, p2 = null, p3 = null){};
function eventChannelSessionAlertClose(p1 = null, p2 = null, p3 = null){};
function eventChannelSessionAlertSent(p1 = null, p2 = null, p3 = null){};
function eventChannelSessionAlertStart(p1 = null, p2 = null, p3 = null){};
function eventMediaInqueueConfirm(p1 = null, p2 = null, p3 = null){};
function eventMediaOutqueueConfirm(p1 = null, p2 = null, p3 = null){};
function onChatroomCreate(p1 = null, p2 = null, p3 = null){};
function onChatroomMemberDelete(p1 = null, p2 = null, p3 = null){};
function onChatroomAddMember(p1 = null, p2 = null, p3 = null){};
function onChatroomQueue(p1 = null, p2 = null, p3 = null){};
function onChatroomUpdate(p1 = null, p2 = null, p3 = null){};
function gUser(){};
function loadChannelList(p1 = null, p2 = null, p3 = null){};
function onSessionOutgoingRinging(p1 = null, p2 = null, p3 = null){};
function onChatRoomEnter(p1 = null, p2 = null, p3 = null){};
function onChatRoomExit(p1 = null, p2 = null, p3 = null){};
function onChatroomForbiden(p1 = null, p2 = null, p3 = null){};
function onHeartbeat(p1 = null, p2 = null, p3 = null){};
function onSessionRelease(p1 = null, p2 = null, p3 = null){};
function getCurrentCallSessionArray(p1 = null, p2 = null, p3 = null){};
function MEDIA_STATE_IDLE(){};
function MEDIA_BUTTON_STATE_IDLE(){};
function onNoticeSession(p1 = null, p2 = null, p3 = null){};
function onMediaStateIdle(p1 = null, p2 = null, p3 = null){};
function str_voice_interrupted_high(){};
function str_apply_timeout(){};
function str_time_speak(){};
function str_voice_network_condition(){};
function onMediaStateTalkDeny(p1 = null, p2 = null, p3 = null){};
function str_listen_not_speak(){};
function str_voice_fully(){};
function onMediaStateTalk(p1 = null, p2 = null, p3 = null){};
function onMediaStateTalkReset(p1 = null, p2 = null, p3 = null){};
function onMediaStateListern(p1 = null, p2 = null, p3 = null){};
function onRecordPlayStart(p1 = null, p2 = null, p3 = null){};
function onRecordPlayStop(p1 = null, p2 = null, p3 = null){};
function onContactPresence(p1 = null, p2 = null, p3 = null){};
function onVideoCaptureGet(p1 = null){};
function onVideoLocalCaptureGet(p1 = null){};
function onVideoStorePush(p1 = null){};
function onVideoReportCaptureLocalFinish(p1 = null){};

function onPushUserNameChanged(p1 = null){};
function onPushOrgNameChanged(p1 = null){};
function onPushUserRoleChanged(p1 = null){};
function onPushOrgStructChanged(p1 = null){};

//function memberList(){};
function CONTACT_STATE_ONLINE(){};
function CONTACT_STATE_OFF_LINE(){};
function onUserMessage(p1 = null, p2 = null, p3 = null){};
function onUserLocaltionChanged(p1 = null, p2 = null, p3 = null){};
function onMessageRecv(p1 = null, p2 = null, p3 = null){};
function onMessageSent(p1 = null, p2 = null, p3 = null){};
function newBroadcast(p1 = null, p2 = null, p3 = null){};
function onDialogClose(p1 = null, p2 = null, p3 = null){};
function jsons(){};
function onSessionDialogPresence(p1 = null, p2 = null, p3 = null){};
function MEDIA_STATE_ON_LINE(){};
function MEDIA_STATE_OFF_LINE(){};
function onSessionDialogMemberChange(p1 = null, p2 = null, p3 = null){};
function onSessionChannelPresence(p1 = null, p2 = null, p3 = null){};
function onSessionChannelUserEnter(p1 = null, p2 = null, p3 = null){};
function onSessionChannelUserExit(p1 = null, p2 = null, p3 = null){};
function onChatroomDelete(p1 = null, p2 = null, p3 = null){};
function onMemberPrioritySave(p1 = null, p2 = null, p3 = null){};
function eventRecRecordStart(p1 = null, p2 = null, p3 = null){};
function eventRecRecordStop(p1 = null, p2 = null, p3 = null){};
function recordDownloadCheck(p1 = null, p2 = null, p3 = null){};
function currentTabSession(){};
function getUserDisplayName(p1 = null, p2 = null, p3 = null){};
function str_speaking(){};
function setResPath(p1 = null, p2 = null, p3 = null){};
function refreshVideoView(){};
/** @constructor */
function MozWebSocket(s){};
function exports(){};
function module(){};
function define(){};
function oids(){};
function CryptoJS(){};
function stohex(){};
function utc(){};
function videoMainGetTiming(p1 = null){};
